version: '3'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=backend/app.py
    networks:
      - cargo-network

networks:
  cargo-network:
    driver: bridge
